### PR TITLE
Correctly handle explicitly-specified annotation processors

### LINKED ISSUE #50: Plugin should warn if user has specified -processor flag, because plugin will not work
see discussion on #45

### PR DESCRIPTION
**Pull request by kelloggm**
Fixes #50.

### CODE REVIEW

File: src/main/groovy/org/checkerframework/gradle/plugin/CheckerFrameworkPlugin.groovy [hunk 1]
```diff
@@ -254,14 +254,34 @@ final class CheckerFrameworkPlugin implements Plugin<Project> {
...
-            // with other auto-discovered annotation processors, because the plugin uses auto-discovery.
-            // We should warn about this: https://github.com/kelloggm/checkerframework-gradle-plugin/issues/50
-            compile.options.annotationProcessorPath = compile.options.annotationProcessorPath.plus(project.files("${project.buildDir}" + manifestLocation))
+
+            // If the user has already specified a processor manually, then
+            // auto-discovery won't work. Instead, augment the list of specified
+            // processors.
+            if (compile.options.compilerArgs.contains('-processor')) {
+              List<String> newCompilerArgs = []
+              for (int i = 0; i < compile.options.compilerArgs.size(); i++) {
```
Comment (mernst) [inline src/main/groovy/org/checkerframework/gradle/plugin/CheckerFrameworkPlugin.groovy]: This loop is a bit ugly.  Why not just test against a call to indexOf?
